"""Materialize the fixed Room 315 world as an HPP/Viser URDF."""

from copy import deepcopy
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]


def generate():
    world = ET.parse(ROOT / "worlds/room_315_only.world")
    result = ET.Element("robot", name="room315_environment")
    result.append(
        ET.Comment("""Generated by scripts/generate_room315_environment.py from
       worlds/room_315_only.world and models/*/model.sdf.\n       Poses are in the MFJA world frame; switches use their initial poses.\n       Mobile shuttles parked below the floor are not part of the fixed cell.""")
    )
    ET.SubElement(result, "link", name="world")
    for include in world.findall("./world/include"):
        model_name = include.findtext("uri").removeprefix("model://")
        if model_name in ("sun", "ground_plane", "room315_shuttle"):
            continue
        model = ET.parse(ROOT / "models" / model_name / "model.sdf").find("model")
        assert len(model.findall("link")) == 1 and not model.findall("joint")
        source = model.find("link")
        for element in (model, source):
            assert all(
                float(v) == 0 for v in element.findtext("pose", "0 0 0 0 0 0").split()
            )
        name = include.findtext("name")
        link = ET.SubElement(result, "link", name=name)
        for collision in source.findall("collision"):
            target = ET.SubElement(link, "collision")
            values = collision.findtext("pose", "0 0 0 0 0 0").split()
            ET.SubElement(
                target, "origin", xyz=" ".join(values[:3]), rpy=" ".join(values[3:])
            )
            geometry = ET.SubElement(target, "geometry")
            shape = collision.find("geometry")[0]
            if shape.tag == "mesh":
                ET.SubElement(
                    geometry,
                    "mesh",
                    filename=shape.findtext("uri").replace(
                        "model://", "package://mfja_3rd_floor_description/models/"
                    ),
                    scale=shape.findtext("scale", "1 1 1"),
                )
            elif shape.tag == "box":
                ET.SubElement(geometry, "box", size=shape.findtext("size"))
            else:
                raise ValueError(shape.tag)
            visual = deepcopy(target)
            visual.tag = "visual"
            material = ET.SubElement(visual, "material", name=name + "_material")
            rgba = source.findtext("visual/material/diffuse", "0.72 0.74 0.78 1")
            if model_name in ("room_315", "carter_droit", "carter_gauche"):
                rgba = " ".join(rgba.split()[:3] + ["0.25"])
            ET.SubElement(material, "color", rgba=rgba)
            link.append(visual)
        joint = ET.SubElement(result, "joint", name=name + "_joint", type="fixed")
        ET.SubElement(joint, "parent", link="world")
        ET.SubElement(joint, "child", link=name)
        values = include.findtext("pose", "0 0 0 0 0 0").split()
        ET.SubElement(
            joint, "origin", xyz=" ".join(values[:3]), rpy=" ".join(values[3:])
        )
    ET.indent(result, space="  ")
    return '<?xml version="1.0"?>\n' + ET.tostring(result, encoding="unicode") + "\n"


if __name__ == "__main__":
    (ROOT / "urdf/room315_environment.urdf").write_text(generate())
